//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int ID { get; set; }
        public int ID_PERSON { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public bool ENABLED { get; set; }
        public System.DateTimeOffset CREATE { get; set; }
    
        public virtual PERSON PERSON { get; set; }
    }
}
